import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{AreaChart,Area,BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend}from'recharts';
import{LayoutDashboard,Boxes,Sparkles,Handshake,Leaf,ArrowUpRight,Clock3,MapPin,Check,ChevronDown,Menu,X,TrendingUp,PackageCheck,CloudSun,Utensils,Users,Search,SlidersHorizontal,Bell,ChevronRight}from'lucide-react';
import'./styles.css';

const nav=[['dashboard','Vue d’ensemble',LayoutDashboard],['stock','Stock & Matching',Boxes],['forecast','Prévisions IA',Sparkles],['partners','Partenaires',Handshake],['impact','Impact',Leaf]];
const monthly=[{m:'Jan',collecte:36.8,route:30.1},{m:'Fév',collecte:41.2,route:35.7},{m:'Mar',collecte:39.4,route:34.8},{m:'Avr',collecte:48.7,route:43.2},{m:'Mai',collecte:53.1,route:48.5},{m:'Juin',collecte:58.4,route:53.7}];
const categories=[{name:'Fruits & légumes',v:18.6},{name:'Produits laitiers',v:11.4},{name:'Viande & poisson',v:8.9},{name:'Boulangerie',v:7.8},{name:'Épicerie sèche',v:6.3},{name:'Surgelés',v:5.4}];
const initialLots=[
 {id:'W2C-2841',cat:'Fruits & légumes',q:420,days:1,city:'Abidjan',score:94,partner:'Socofrais',match:92,km:6.5,status:'À confirmer'},
 {id:'W2C-2839',cat:'Produits laitiers',q:185,days:2,city:'Bouaké',score:82,partner:'Dabali Express',match:88,km:4.2,status:'À confirmer'},
 {id:'W2C-2837',cat:'Boulangerie',q:96,days:1,city:'Abidjan',score:91,partner:'Marché Adjamé Central',match:86,km:2.8,status:'À confirmer'},
 {id:'W2C-2834',cat:'Épicerie sèche',q:310,days:12,city:'Yamoussoukro',score:48,partner:'Ivoire Distribution',match:84,km:8.1,status:'À confirmer'},
 {id:'W2C-2831',cat:'Viande & poisson',q:145,days:3,city:'San-Pédro',score:76,partner:'FreshLink CI',match:90,km:5.7,status:'À confirmer'}];
const forecast=[{m:'Juil',fruits:20.2,laitiers:12.2,viande:9.4},{m:'Août',fruits:22.8,laitiers:12.8,viande:10.1},{m:'Sept',fruits:21.1,laitiers:13.6,viande:10.8},{m:'Oct',fruits:23.9,laitiers:14.1,viande:11.2},{m:'Nov',fruits:25.4,laitiers:15.3,viande:12.4},{m:'Déc',fruits:29.8,laitiers:17.8,viande:14.9}];
const partnerData=[
 {name:'Socofrais',tag:'Grossiste frais',city:'Abidjan',used:64,demand:'Fruits, légumes & laitier',km:6.5,score:4.9,initials:'SO'},
 {name:'Dabali Express',tag:'Livraison urbaine',city:'Bouaké',used:78,demand:'Plats frais & boulangerie',km:4.2,score:4.8,initials:'DE'},
 {name:'Marché Adjamé Central',tag:'Réseau de revendeurs',city:'Abidjan',used:52,demand:'Tous produits frais',km:2.8,score:4.7,initials:'MA'},
 {name:'Ivoire Distribution',tag:'Distributeur régional',city:'Yamoussoukro',used:43,demand:'Épicerie & surgelés',km:8.1,score:4.6,initials:'ID'},
 {name:'FreshLink CI',tag:'Chaîne du froid',city:'San-Pédro',used:71,demand:'Viande & poisson',km:5.7,score:4.9,initials:'FL'},
 {name:'Nourrir Demain',tag:'Cuisine collective',city:'Abidjan',used:37,demand:'Fruits & épicerie',km:9.3,score:4.8,initials:'ND'}];

const fmt=n=>new Intl.NumberFormat('fr-FR').format(n);
function Logo(){return <div className="logo"><span><Leaf size={19}/></span><b>Waste<span>2</span>Cash</b></div>}
function Header({page,setMenu}){return <header><button className="mobile-menu" onClick={()=>setMenu(true)}><Menu/></button><div><div className="eyebrow">WASTE2CASH CONTROL CENTER</div><h1>{nav.find(n=>n[0]===page)?.[1]}</h1></div><div className="header-actions"><button className="icon-btn"><Bell size={19}/><i/></button><div className="avatar">AK</div><div className="profile"><b>Amadou Koné</b><span>Administrateur</span></div></div></header>}
function Sidebar({page,setPage,menu,setMenu}){return <aside className={menu?'open':''}><div className="side-head"><Logo/><button onClick={()=>setMenu(false)}><X/></button></div><div className="workspace"><div className="workspace-icon">W2</div><div><small>ESPACE DE TRAVAIL</small><b>Côte d’Ivoire</b></div><ChevronDown size={16}/></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMenu(false)}}><Icon size={20}/>{label}{page===id&&<ChevronRight size={16}/>}</button>)}</nav><div className="side-impact"><span><Leaf size={17}/> IMPACT CE MOIS</span><b>53,7 t</b><small>d’invendus valorisés</small><div><i style={{width:'92%'}}/></div><p>92% de l’objectif mensuel</p></div><div className="side-foot"><span>●</span> Système opérationnel</div></aside>}
const Card=({children,className=''})=><div className={'card '+className}>{children}</div>;
function Kpi({icon:Icon,label,value,unit,delta,color='blue'}){return <Card className="kpi"><div className={'kpi-icon '+color}><Icon size={21}/></div><div className="kpi-label">{label}</div><div className="kpi-value">{value}<small>{unit}</small></div><div className="kpi-delta"><ArrowUpRight size={14}/>{delta}<span>vs mois dernier</span></div></Card>}
function ChartTip({active,payload,label}){if(!active||!payload?.length)return null;return <div className="chart-tip"><b>{label}</b>{payload.map((p,i)=><span key={i}><i style={{background:p.color}}/>{p.name}: <strong>{p.value} t</strong></span>)}</div>}
function Dashboard(){return <div className="page"><div className="hero"><div><span className="live"><i/> DONNÉES EN DIRECT</span><h2>Bonjour Amadou,</h2><p>Voici la performance de votre réseau de valorisation ce mois-ci.</p></div><button className="date"><Clock3 size={16}/> Juin 2026 <ChevronDown size={15}/></button></div><div className="kpi-grid"><Kpi icon={Boxes} label="STOCK COLLECTÉ" value="58,4" unit="tonnes" delta="12,5%"/><Kpi icon={PackageCheck} label="TAUX DE VALORISATION" value="91,9" unit="%" delta="4,2%" color="green"/><Kpi icon={Clock3} label="TEMPS MOYEN DE MATCH" value="6,8" unit="heures" delta="18% plus rapide"/><Kpi icon={Leaf} label="CO₂ ÉVITÉ ESTIMÉ" value="124" unit="tCO₂e" delta="14,1%" color="green"/></div><div className="chart-grid"><Card className="big-chart"><Title title="Performance de collecte" sub="Volumes collectés et valorisés — 6 derniers mois" right={<LegendPills/>}/><ResponsiveContainer width="100%" height={275}><AreaChart data={monthly} margin={{top:20,right:5,left:-17,bottom:0}}><defs><linearGradient id="blueFade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1f5fbf" stopOpacity=".22"/><stop offset="1" stopColor="#1f5fbf" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#edf1f6" vertical={false}/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} unit=" t"/><Tooltip content={<ChartTip/>}/><Area name="Collecté" type="monotone" dataKey="collecte" stroke="#1f5fbf" strokeWidth={3} fill="url(#blueFade)"/><Area name="Valorisé" type="monotone" dataKey="route" stroke="#2e7d32" strokeWidth={3} fill="transparent"/></AreaChart></ResponsiveContainer></Card><Card><Title title="Volume par catégorie" sub="Répartition du stock collecté"/><ResponsiveContainer width="100%" height={275}><BarChart data={categories} layout="vertical" margin={{top:10,right:15,left:20,bottom:0}}><CartesianGrid stroke="#edf1f6" horizontal={false}/><XAxis type="number" axisLine={false} tickLine={false} unit=" t"/><YAxis type="category" dataKey="name" axisLine={false} tickLine={false} width={125} fontSize={11}/><Tooltip cursor={{fill:'#f5f8fc'}} content={<ChartTip/>}/><Bar name="Volume" dataKey="v" fill="#1f5fbf" radius={[0,6,6,0]} barSize={17}/></BarChart></ResponsiveContainer></Card></div><Card className="activity"><Title title="Activité récente" sub="Dernières opérations du réseau" right={<button className="link-btn">Voir tout <ArrowUpRight size={15}/></button>}/><div className="activity-row"><span className="activity-icon green"><Check/></span><div><b>Lot W2C-2840 valorisé avec succès</b><p>320 kg de fruits & légumes livrés à Socofrais</p></div><small>Il y a 12 min</small></div><div className="activity-row"><span className="activity-icon blue"><Sparkles/></span><div><b>Nouveau match IA à 94%</b><p>Lot W2C-2841 recommandé à Socofrais</p></div><small>Il y a 28 min</small></div></Card></div>}
function Title({title,sub,right}){return <div className="card-title"><div><h3>{title}</h3>{sub&&<p>{sub}</p>}</div>{right}</div>}
function LegendPills(){return <div className="legend"><span><i className="lb"/>Collecté</span><span><i className="lg"/>Valorisé</span></div>}
function Stock(){const[lots,setLots]=useState(initialLots);const[filter,setFilter]=useState('Toutes');const[search,setSearch]=useState('');const confirm=id=>setLots(lots.map(l=>l.id===id?{...l,status:'Matché'}:l));const shown=lots.filter(l=>(filter==='Toutes'||l.cat===filter)&&(l.id.toLowerCase().includes(search.toLowerCase())||l.city.toLowerCase().includes(search.toLowerCase())));return <div className="page"><div className="page-heading"><div><span className="live"><i/> 5 LOTS À TRAITER</span><h2>Stock disponible</h2><p>Priorisez et affectez chaque lot grâce aux recommandations IA.</p></div><button className="primary"><Sparkles size={17}/> Lancer le matching automatique</button></div><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Rechercher un lot ou une ville…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filters"><SlidersHorizontal size={17}/>{['Toutes','Fruits & légumes','Produits laitiers','Boulangerie'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><Card className="table-card"><div className="lots-table"><div className="lot-row head"><span>LOT / CATÉGORIE</span><span>QUANTITÉ</span><span>EXPIRATION</span><span>COLLECTE</span><span>PRIORITÉ IA</span><span>MEILLEUR MATCH</span><span>ACTION</span></div>{shown.map(l=><div className="lot-row" key={l.id}><span className="lot-name"><b>{l.id}</b><small>{l.cat}</small></span><span><b>{fmt(l.q)} kg</b></span><span><em className={l.days<=1?'urgent':l.days<=3?'medium':'calm'}>{l.days} jour{l.days>1?'s':''}</em></span><span className="city"><MapPin size={15}/>{l.city}</span><span><strong className={'score s'+(l.score>88?'high':l.score>65?'mid':'low')}>{l.score}</strong><small className="score-label">{l.score>88?'Urgent':l.score>65?'Élevée':'Normale'}</small></span><span className="match"><Sparkles size={16}/><b>{l.partner}</b><small>{l.match}% match · {l.km} km</small></span><span>{l.status==='Matché'?<button className="matched"><Check size={16}/> Matché</button>:<button className="confirm" onClick={()=>confirm(l.id)}>Confirmer</button>}</span></div>)}</div></Card><div className="ai-note"><Sparkles/><div><b>Comment l’IA priorise-t-elle les lots ?</b><p>Le score combine la date limite, la quantité, la demande partenaire, la distance et les conditions de stockage issues du modèle Waste2Cash.</p></div><span>Modèle actif · v2.4</span></div></div>}
function Forecast(){return <div className="page"><div className="page-heading"><div><span className="ai-badge"><Sparkles size={14}/> MODÈLE PRÉDICTIF ACTIF</span><h2>Anticiper les volumes, optimiser les capacités.</h2><p>Prévisions alimentées par l’historique de collecte et les signaux saisonniers.</p></div><button className="date"><Clock3 size={16}/> Horizon : 6 mois <ChevronDown size={15}/></button></div><div className="forecast-kpis"><Card><span>VOLUME TOTAL PRÉVU</span><b>214,6 t</b><small><TrendingUp/> +16,8% vs période précédente</small></Card><Card><span>CATÉGORIE EN HAUSSE</span><b>Fruits & légumes</b><small>+24,2% d’ici décembre</small></Card><Card><span>CONFIANCE DU MODÈLE</span><b>92,4%</b><small>R² sur données de validation</small></Card></div><Card className="forecast-chart"><Title title="AI Forecast — 6 prochains mois" sub="Volume d’invendus attendu par catégorie (tonnes)" right={<span className="updated">Mis à jour aujourd’hui, 06:00</span>}/><ResponsiveContainer width="100%" height={370}><LineChart data={forecast} margin={{top:25,right:20,left:-10,bottom:5}}><CartesianGrid stroke="#e9eef5" vertical={false}/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} unit=" t"/><Tooltip content={<ChartTip/>}/><Legend/><Line name="Fruits & légumes" type="monotone" dataKey="fruits" stroke="#1f5fbf" strokeWidth={3} dot={{r:4}}/><Line name="Produits laitiers" type="monotone" dataKey="laitiers" stroke="#2e7d32" strokeWidth={3} dot={{r:4}}/><Line name="Viande & poisson" type="monotone" dataKey="viande" stroke="#7c8da6" strokeWidth={3} dot={{r:4}}/></LineChart></ResponsiveContainer></Card><div className="forecast-info"><span><Sparkles/></span><div><b>La donnée au service de la planification</b><p>Les prévisions sont générées à partir des données historiques de collecte grâce au machine learning. Elles aident les partenaires et responsables de magasin à planifier leurs capacités en amont.</p></div><button>Consulter la méthodologie <ArrowUpRight size={15}/></button></div></div>}
function Partners(){return <div className="page"><div className="page-heading"><div><span className="eyebrow">RÉSEAU DE VALORISATION</span><h2>Des partenaires engagés, partout en Côte d’Ivoire.</h2><p>Suivez la capacité et la demande de votre réseau en temps réel.</p></div><button className="primary"><Users size={17}/> Ajouter un partenaire</button></div><div className="partner-summary"><div><b>24</b><span>partenaires actifs</span></div><div><b>68%</b><span>capacité moyenne utilisée</span></div><div><b>4,8/5</b><span>satisfaction moyenne</span></div><div><b>6</b><span>villes couvertes</span></div></div><div className="partner-grid">{partnerData.map(p=><Card className="partner-card" key={p.name}><div className="partner-head"><span className="partner-logo">{p.initials}</span><div><h3>{p.name}</h3><p>{p.tag} · {p.city}</p></div><button>•••</button></div><div className="capacity"><span>Capacité de stockage utilisée <b>{p.used}%</b></span><div><i style={{width:p.used+'%'}}/></div></div><div className="partner-meta"><div><span>DEMANDE HABITUELLE</span><b>{p.demand}</b></div><div><span>DISTANCE</span><b><MapPin size={14}/>{p.km} km</b></div></div><div className="partner-foot"><span className="stars">★★★★★</span><b>{p.score}</b><button>Voir le profil <ChevronRight/></button></div></Card>)}</div></div>}
function Impact(){return <div className="page impact-page"><div className="impact-hero"><div><span><Leaf size={15}/> NOTRE IMPACT</span><h2>Chaque kilo valorisé<br/>nourrit un avenir meilleur.</h2><p>Waste2Cash transforme les pertes alimentaires en valeur économique, sociale et environnementale.</p></div><div className="impact-circle"><Leaf/><b>91,9%</b><span>valorisés</span></div></div><div className="impact-grid"><Card><Utensils/><span>REPAS ÉQUIVALENTS SAUVÉS</span><b>428 600</b><p>+52 400 ce trimestre</p></Card><Card><CloudSun/><span>ÉMISSIONS DE CO₂ ÉVITÉES</span><b>1 240 <small>tCO₂e</small></b><p>L’équivalent de 270 voitures/an</p></Card><Card><Handshake/><span>ORGANISATIONS PARTENAIRES</span><b>24</b><p>Dans 6 villes ivoiriennes</p></Card><Card><Users/><span>FAMILLES TOUCHÉES</span><b>18 750</b><p>Impact direct et indirect</p></Card></div><div className="mission"><div><span>NOTRE TRAJECTOIRE</span><h3>Un moteur commercial.<br/>Une ambition nationale.</h3></div><div><p>Notre activité commerciale finance aujourd’hui la collecte, la technologie et les opérations. Ce socle rentable prouve qu’impact et performance économique peuvent avancer ensemble.</p><p>Demain, les financements publics et ONG nous permettront de déployer ce modèle à l’échelle nationale, jusque dans les zones où l’équation logistique reste la plus difficile.</p><button className="primary">Découvrir notre vision <ArrowUpRight size={16}/></button></div></div><div className="sdg"><span>Notre contribution aux Objectifs de développement durable</span><div><i>2</i><b>Faim « zéro »</b></div><div><i>12</i><b>Consommation responsable</b></div><div><i>13</i><b>Action climatique</b></div></div></div>}
function App(){const[page,setPage]=useState('dashboard');const[menu,setMenu]=useState(false);return <><Sidebar page={page} setPage={setPage} menu={menu} setMenu={setMenu}/><main><Header page={page} setMenu={setMenu}/>{page==='dashboard'?<Dashboard/>:page==='stock'?<Stock/>:page==='forecast'?<Forecast/>:page==='partners'?<Partners/>:<Impact/>}</main>{menu&&<div className="overlay" onClick={()=>setMenu(false)}/>}</>}
createRoot(document.getElementById('root')).render(<App/>);
